### ISSUE TITLE
Unable to download images

### ISSUE THREAD

**Issue by BinahHu** [KevinLight831/P9D#1]
Thank you for your excellent work!

I try to download the train images with the scripts, but got response code 403, looks like we do not have the access to those images. Do we need to apply for the access?

Besides, there are some minor bugs in download_images_train.py, the train.json is organized first by high level category names and then the item ids, but the script assumes it is already organized by item ids.

**Comment by KevinLight831** [comment]
Thank you very much for your valuable advice.

1. You can verify the accessibility of 'image_link' or 'oss_url' by copying the link and pasting it into your browser. However, I was only able to view the 'image_link' image on my browser. Therefore, I modified the download link for all scripts.
2. The 'item_id' is the only ID for all images.  To align with the organizational structure of the 'train.json', I have made modifications to the 'download_images_train.py' script.
3. All images can also be accessed by downloading the zip directly.

**Comment by BinahHu** [comment]
Thanks, 'image_link' works.
