### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Areeb2735** [KevinLight831/P9D#2]
Hi. I am trying to download the P9D dataset. I have downloaded the JSON files and changed the paths in the download_images_train.py file, but when I execute, I am facing the following error. Can you please check and let me know what I can do to download the dataset. 

![image](https://github.com/user-attachments/assets/b3ccf6e4-96f4-40bd-b503-4024b4ace95d)

Error when running download_images_train.py

Thanks.

**Comment by KevinLight831** [comment]
This is a bug where the program is looking for an index, not a bug where the download link cannot be accessed. I think it's best to check whether the index exists in train_id_info. It is also recommended to run download_images_train.py first and then download_images_check.py

**Comment by Areeb2735** [comment]
Thanks for the response. 

The keys of train_id_info are:
dict_keys(['食品/保健', '家居用品', '家装家饰', '美容护理', '母婴', '服饰鞋包', '3C数码', '车品配件', '运动/户外'])

As a result, train_id_info[item_id]["image_link"] results in the error as item_id is 564970491434, which exists in the dict but under the key '食品/保健.'

how was line 22 in download_images_train.py working?

**Comment by KevinLight831** [comment]
Maybe you could review the logic of the code. I'm caught up with preparing for my oral defense in a few days, so I might not be able to revisit this code and provide answers in the short term. I sincerely appreciate your attention and understanding. Sorry...
